version: "3.7"

services:

  pgadmin:
    container_name: ${PROJECT_NAME:-example}_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - base-net
    restart: unless-stopped

#  front:
#    image: igor368/parking-app-angular:dev

volumes:
  pgadmin: